### PR TITLE
LPS-116351 Test fix

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-116351

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by marcosapmf** [comment]
Pull request forwarded to https://github.com/natocesarrego/liferay-portal/pull/759

**Pull request closed without merging**
