### PR TITLE
LPS-115417 baseline

### PR DESCRIPTION
**Pull request by marcosapmf**

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
it looks like the upgrade bundle cannot start up in this pr, this isnt happening upstream, rerunning an upgrade test for you to check if this could possibly be a fluke/race condition
ci:test:upgrade

**Comment by kyle-miho** [comment]
ci:test:upgrade

**Comment by marcosapmf** [comment]
Hey @kyle-miho.
It looks like the problem was on the way I implemented the upgrade step. @rafaprax told me that [here](https://liferay.slack.com/archives/C19PWQ74J/p1594413850109300?thread_ts=1594405004.104800&cid=C19PWQ74J).

Therefore, I rewrote the code so that it use SQL queries instead of the DDM*Service calls. I'm going ahead and push that changes and rerunning the relevant suit.

Thanks ;)

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Pull request closed without merging**
