### PR TITLE
LRAC 10912

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
resent to https://github.com/marcellustavares/liferay-portal/pull/1986

**Pull request closed without merging**
