### PR TITLE
LPS-118626 Increase schema version

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-118626

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by marcosapmf** [comment]
Pull request submitted in https://github.com/natocesarrego/liferay-portal/pull/741

**Pull request closed without merging**
