### PR TITLE
LRAC-10637

### PR DESCRIPTION
**Pull request by marcosapmf**
- LRAC-10636 analytics-dxp-entities-exporter-api init
- LRAC-10636 analytics-dxp-entities-exporter-impl init
- LRAC-10636 analytics-dxp-entities-exporter-impl openAPI schema and config
- LRAC-10636 buildREST
- LRAC-10636 DXPEntityDTOConverter
- LRAC-10636 check exclusion
- LRAC-10636 convert contact and user
- LRAC-10636 convert group
- LRAC-10636 convert organization
- LRAC-10636 convert role
- LRAC-10636 convert team
- LRAC-10636 convert user group
- LRAC-10637 build.gradle
- LRAC-10637 export package
- LRAC-10637 retrieve dxp entities page
- LRAC-10637 dispatch executor
- LRAC-10637 dxp entities batch engine task item delegates
- LRAC-10637 baseline

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @marcosapmf, can you please check if these failures are related to your changes? Thanks

**Comment by marcosapmf** [comment]
resent https://github.com/marcosapmf/liferay-portal/pull/295

**Pull request closed without merging**
