### PR TITLE
LPS-120007 Avoid triggering the field change event when it is not necessary

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related issues:  https://issues.liferay.com/browse/LPS-120007 and https://issues.liferay.com/browse/LPS-119840

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:app-builder

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
