### PR TITLE
LPS-119931 Handle the case when the stored value is already in JSONObject format

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-119931

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by marcosapmf** [comment]
Forwarded to https://github.com/marcosapmf/liferay-portal/pull/103

**Pull request closed without merging**
