### PR TITLE
LPS-112104 baseline

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-112104

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by marcosapmf** [comment]
Pull request forwarded to https://github.com/natocesarrego/liferay-portal/pull/708. [See changes here.](https://github.com/marcosapmf/liferay-portal/compare/b73f2653a9dd~2...b73f2653a9dd)

**Pull request closed without merging**
