### PR TITLE
LPS-121225 avoid close sidebar when clicking inside of cke dialog

### PR DESCRIPTION
**Pull request by marcosapmf**
Related Issue: https://issues.liferay.com/browse/LPS-121225

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:stop

**Comment by marcosapmf** [comment]
test

**Comment by marcosapmf** [comment]
test

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
test

**Comment by marcosapmf** [comment]
test

**Comment by marcosapmf** [comment]
test

**Comment by marcosapmf** [comment]
test

**Comment by marcosapmf** [comment]
test

**Comment by marcosapmf** [comment]
test

**Comment by marcosapmf** [comment]
test

**Pull request closed without merging**
