### PR TITLE
LPS-121827 set field reference initial value when adding an element set

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-121830
https://issues.liferay.com/browse/LPS-121827

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by marcosapmf** [comment]
@carolmariaabb, reenviei o pr pra tu (https://github.com/carolmariaabb/liferay-portal/pull/231) já revisado e com o que estava faltando da minha parte. Valeu :D

**Pull request closed without merging**
