### PR TITLE
LRAC-10637

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
Hi @marcosapmf, i reorganized the commits so it's easier to break down the PR later. I already sent to marcellus for review up to https://github.com/marcosapmf/liferay-portal/commit/8abd20a326563f635d023cbe0cc6aab8b1413757

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @rachaelkoestartyo, can you please fix the source formatter issues and resend? Thanks

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @rachaelkoestartyo, can you please check if these failures are related to your changes? Thanks

**Comment by rachaelkoestartyo** [comment]
https://github.com/marcosapmf/liferay-portal/pull/297

**Pull request closed without merging**
