### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
Hey @marcelabc, can you please fix the source formatter issues and resend? Thanks

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Pull request closed without merging**
